version: '3'

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-backend
    ports:
      - "5252:5252"
    restart: always

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-frontend
    ports:
      - "9000:9000"
    depends_on:
      - back-end
    restart: always