# Utilisation de l'image Ubuntu la plus récente comme base
FROM ubuntu:latest

# Mise à jour des dépôts APT
RUN apt-get update

# Mise à niveau des logiciels installés
RUN apt-get upgrade -y

# Commande à exécuter lorsque le conteneur démarre
CMD ["echo", "Hello, World!"]
